DROP SCHEMA dadosPuros CASCADE;
CREATE SCHEMA dadosPuros;

CREATE TABLE dadosPuros.cabecalho (
    nomeColuna text,
    perguntaColuna text
);

INSERT INTO dadosPuros.cabecalho (nomeColuna, perguntaColuna)
VALUES
    ('data_001','ID da resposta'),
    ('data_002','Data de envio'),
    ('data_003','Última página'),
    ('data_004','Idioma inicial'),
    ('data_005','Data de início'),
    ('data_006','Data da última ação'),
    ('data_007','1) Sua entrega será melhor definida como:'),
    ('data_008','A1) Como melhor definir o tipo de produto a ser oferecido?'),
    ('data_009','A1) Como melhor definir o tipo de produto a ser oferecido? [Outros]'),
    ('data_010','A1.1) Seu curso será na modalidade:'),
    ('data_011','A1.2) Seu curso será no formato:'),
    ('data_012','A1.2) Seu curso será no formato: [Outros]'),
    ('data_013','A1.3) Seu evento será do tipo:'),
    ('data_014','A1.3) Seu evento será do tipo: [Outros]'),
    ('data_015','A1.4) Em qual formato o conteúdo será apresentado?'),
    ('data_016','A1.4) Em qual formato o conteúdo será apresentado? [Outros]'),
    ('data_017','A1.5) Sua bolsa será do tipo:'),
    ('data_018','A1.5) Sua bolsa será do tipo: [Outros]'),
    ('data_019','A2) Nome do seu produto:'),
    ('data_020','A3) Público alvo: [Enap]'),
    ('data_021','A3) Público alvo: [Servidores(as) Públicos(as)]'),
    ('data_022','A3) Público alvo: [Outro(s) Órgão(s) de Governo]'),
    ('data_023','A3) Público alvo: [Universidade(s)]'),
    ('data_024','A3) Público alvo: [Outra(s) Escola(s) de Governo]'),
    ('data_025','A3) Público alvo: [Sociedade Civil]'),
    ('data_026','A3) Público alvo: [Outros]'),
    ('data_027','A3.1) Deseja especificar o público dentro da Enap? [Não desejo especificar]'),
    ('data_028','A3.1) Deseja especificar o público dentro da Enap? [Todos os servidores]'),
    ('data_029','A3.1) Deseja especificar o público dentro da Enap? [Presidência]'),
    ('data_030','A3.1) Deseja especificar o público dentro da Enap? [Gabinete]'),
    ('data_031','A3.1) Deseja especificar o público dentro da Enap? [Diretorias]'),
    ('data_032','A3.1) Deseja especificar o público dentro da Enap? [Coordenações]'),
    ('data_033','A3.1) Deseja especificar o público dentro da Enap? [Outra especificação]'),
    ('data_034','A3.1.1) Infome aqui a especificação do público alvo dentro da Enap não contemplada na lista da questão A3.1.'),
    ('data_035','A3.2) Deseja especificar em qual esfera se encontram os servidores públicos que fazem parte de seu público alvo? [Não desejo especificar]'),
    ('data_036','A3.2) Deseja especificar em qual esfera se encontram os servidores públicos que fazem parte de seu público alvo? [Federal]'),
    ('data_037','A3.2) Deseja especificar em qual esfera se encontram os servidores públicos que fazem parte de seu público alvo? [Estadual]'),
    ('data_038','A3.2) Deseja especificar em qual esfera se encontram os servidores públicos que fazem parte de seu público alvo? [Municipal]'),
    ('data_039','A3.3) Deseja especificar em qual carreira se encontram os servidores públicos que fazem parte de seu público alvo? [Não desejo especificar]'),
    ('data_040','A3.3) Deseja especificar em qual carreira se encontram os servidores públicos que fazem parte de seu público alvo? [Carreiras Do Ciclo De Gestão]'),
    ('data_041','A3.3) Deseja especificar em qual carreira se encontram os servidores públicos que fazem parte de seu público alvo? [ACE]'),
    ('data_042','A3.3) Deseja especificar em qual carreira se encontram os servidores públicos que fazem parte de seu público alvo? [AFFC]'),
    ('data_043','A3.3) Deseja especificar em qual carreira se encontram os servidores públicos que fazem parte de seu público alvo? [AIE]'),
    ('data_044','A3.3) Deseja especificar em qual carreira se encontram os servidores públicos que fazem parte de seu público alvo? [APO]'),
    ('data_045','A3.3) Deseja especificar em qual carreira se encontram os servidores públicos que fazem parte de seu público alvo? [ATI]'),
    ('data_046','A3.3) Deseja especificar em qual carreira se encontram os servidores públicos que fazem parte de seu público alvo? [ATPS]'),
    ('data_047','A3.3) Deseja especificar em qual carreira se encontram os servidores públicos que fazem parte de seu público alvo? [EIE]'),
    ('data_048','A3.3) Deseja especificar em qual carreira se encontram os servidores públicos que fazem parte de seu público alvo? [EPPGG]'),
    ('data_049','A3.3) Deseja especificar em qual carreira se encontram os servidores públicos que fazem parte de seu público alvo? [Outra(s) Carreira(s)]'),
    ('data_050','A3.3.1) Especifique aqui carreiras dos servidores que fazem parte do seu público alvo que não se encontram na lista da questão A3.3.'),
    ('data_051','A3.4) Deseja especificar em qual(is) cargo(s) abaixo ou equivalente(s) se encontram os servidores públicos alvo do seu produto? [Não desejo especificar]'),
    ('data_052','A3.4) Deseja especificar em qual(is) cargo(s) abaixo ou equivalente(s) se encontram os servidores públicos alvo do seu produto? [DAS 6]'),
    ('data_053','A3.4) Deseja especificar em qual(is) cargo(s) abaixo ou equivalente(s) se encontram os servidores públicos alvo do seu produto? [DAS 5]'),
    ('data_054','A3.4) Deseja especificar em qual(is) cargo(s) abaixo ou equivalente(s) se encontram os servidores públicos alvo do seu produto? [DAS/FCPE 4]'),
    ('data_055','A3.4) Deseja especificar em qual(is) cargo(s) abaixo ou equivalente(s) se encontram os servidores públicos alvo do seu produto? [DAS/FCPE 3]'),
    ('data_056','A3.4) Deseja especificar em qual(is) cargo(s) abaixo ou equivalente(s) se encontram os servidores públicos alvo do seu produto? [DAS/FCPE 2]'),
    ('data_057','A3.4) Deseja especificar em qual(is) cargo(s) abaixo ou equivalente(s) se encontram os servidores públicos alvo do seu produto? [DAS/FCPE 1]'),
    ('data_058','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Não desejo especificar]'),
    ('data_059','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Administração Pública]'),
    ('data_060','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Compras Públicas]'),
    ('data_061','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Comunicação]'),
    ('data_062','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Direito]'),
    ('data_063','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Economia]'),
    ('data_064','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Equidade de Gênero]'),
    ('data_065','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Ética]'),
    ('data_066','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Fiscalização e Controle]'),
    ('data_067','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Gestão de Pessoas]'),
    ('data_068','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Gestão Pública]'),
    ('data_069','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Inclusao de Pessoas com Deficiência]'),
    ('data_070','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Infraestrutura]'),
    ('data_071','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Inovação]'),
    ('data_072','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Liderança]'),
    ('data_073','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Logística]'),
    ('data_074','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Orçamento/Finanças]'),
    ('data_075','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Políticas Sociais]'),
    ('data_076','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Projetos]'),
    ('data_077','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Regulação]'),
    ('data_078','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Tecnologia da Informação]'),
    ('data_079','A3.5) Deseja especificar em qual área os servidores públicos alvo de seu produto trabalham? [Outra Área]'),
    ('data_080','A3.5.1) Especifique aqui a(s) área(s) dos servidores públicos alvo de seu produto que não constam na lista da questão A3.5.'),
    ('data_081','A3.6) Deseja especificar que órgão(s) do governo(s) são o alvo de seu produto? [Não desejo especificar]'),
    ('data_082','A3.6) Deseja especificar que órgão(s) do governo(s) são o alvo de seu produto? [Ministério do Planejamento]'),
    ('data_083','A3.6) Deseja especificar que órgão(s) do governo(s) são o alvo de seu produto? [Outro(s) Órgão(s)]'),
    ('data_084','A3.6.1) Deseja especificar que órgão(s) do governo que não constam na lista da questão A3.6 fazem parte do público alvo?'),
    ('data_085','A3.7) Deseja especificar qual(is) universidade(s) faz(em) parte do público alvo desse produto?'),
    ('data_086','A3.8) Deseja especificar qual(is) escola(s) de governo faz(em) parte do público alvo desse produto?'),
    ('data_087','A3.9) Deseja especificar que parte da sociedade civil faz parte do público alvo?'),
    ('data_088','A3.10) Deseja especificar o público alvo informado no campo ‘Outros’ da questão A3?'),
    ('data_089','A4) Informe um ou mais temas que se relacionam com o seu produto. [Administração Pública]'),
    ('data_090','A4) Informe um ou mais temas que se relacionam com o seu produto. [Compras Públicas]'),
    ('data_091','A4) Informe um ou mais temas que se relacionam com o seu produto. [Comunicação]'),
    ('data_092','A4) Informe um ou mais temas que se relacionam com o seu produto. [Direito]'),
    ('data_093','A4) Informe um ou mais temas que se relacionam com o seu produto. [Economia]'),
    ('data_094','A4) Informe um ou mais temas que se relacionam com o seu produto. [Equidade de Gênero]'),
    ('data_095','A4) Informe um ou mais temas que se relacionam com o seu produto. [Ética]'),
    ('data_096','A4) Informe um ou mais temas que se relacionam com o seu produto. [Fiscalização e Controle]'),
    ('data_097','A4) Informe um ou mais temas que se relacionam com o seu produto. [Gestão de Pessoas]'),
    ('data_098','A4) Informe um ou mais temas que se relacionam com o seu produto. [Gestão Pública]'),
    ('data_099','A4) Informe um ou mais temas que se relacionam com o seu produto. [Inclusao de Pessoas com Deficiência]'),
    ('data_100','A4) Informe um ou mais temas que se relacionam com o seu produto. [Infraestrutura]'),
    ('data_101','A4) Informe um ou mais temas que se relacionam com o seu produto. [Inovação]'),
    ('data_102','A4) Informe um ou mais temas que se relacionam com o seu produto. [Liderança]'),
    ('data_103','A4) Informe um ou mais temas que se relacionam com o seu produto. [Logística]'),
    ('data_104','A4) Informe um ou mais temas que se relacionam com o seu produto. [Orçamento/Finanças]'),
    ('data_105','A4) Informe um ou mais temas que se relacionam com o seu produto. [Políticas Sociais]'),
    ('data_106','A4) Informe um ou mais temas que se relacionam com o seu produto. [Projetos]'),
    ('data_107','A4) Informe um ou mais temas que se relacionam com o seu produto. [Regulação]'),
    ('data_108','A4) Informe um ou mais temas que se relacionam com o seu produto. [Tecnologia da Informação]'),
    ('data_109','A4) Informe um ou mais temas que se relacionam com o seu produto. [Outros]'),
    ('data_110','A5) Instituições envolvidas:'),
    ('data_111','A6) Fonte de orçamento: [Orçamento da Enap]'),
    ('data_112','A6) Fonte de orçamento: [TED]'),
    ('data_113','A6) Fonte de orçamento: [Patrocínio]'),
    ('data_114','A6) Fonte de orçamento: [Não Precisa de Orçamento]'),
    ('data_115','A6) Fonte de orçamento: [A Definir]'),
    ('data_116','A6) Fonte de orçamento: [Outros]'),
    ('data_117','A7) Quantidade de vezes que o produto deve ser entregue ao longo do ano:'),
    ('data_118','A7) Quantidade de vezes que o produto deve ser entregue ao longo do ano: [Outros]'),
    ('data_119','A7.1 - Informe a quantidade:'),
    ('data_120','A8) Mês de entrega: [JAN]'),
    ('data_121','A8) Mês de entrega: [FEV]'),
    ('data_122','A8) Mês de entrega: [MAR]'),
    ('data_123','A8) Mês de entrega: [ABR]'),
    ('data_124','A8) Mês de entrega: [MAI]'),
    ('data_125','A8) Mês de entrega: [JUN]'),
    ('data_126','A8) Mês de entrega: [JUL]'),
    ('data_127','A8) Mês de entrega: [AGO]'),
    ('data_128','A8) Mês de entrega: [SET]'),
    ('data_129','A8) Mês de entrega: [OUT]'),
    ('data_130','A8) Mês de entrega: [NOV]'),
    ('data_131','A8) Mês de entrega: [DEZ]'),
    ('data_132','B1) Selecione um ou mais temas relacionados ao serviço [Administração Pública]'),
    ('data_133','B1) Selecione um ou mais temas relacionados ao serviço [Compras Públicas]'),
    ('data_134','B1) Selecione um ou mais temas relacionados ao serviço [Comunicação]'),
    ('data_135','B1) Selecione um ou mais temas relacionados ao serviço [Direito]'),
    ('data_136','B1) Selecione um ou mais temas relacionados ao serviço [Economia]'),
    ('data_137','B1) Selecione um ou mais temas relacionados ao serviço [Equidade de Gênero]'),
    ('data_138','B1) Selecione um ou mais temas relacionados ao serviço [Ética]'),
    ('data_139','B1) Selecione um ou mais temas relacionados ao serviço [Fiscalização e Controle]'),
    ('data_140','B1) Selecione um ou mais temas relacionados ao serviço [Gestão de Pessoas]'),
    ('data_141','B1) Selecione um ou mais temas relacionados ao serviço [Gestão Pública]'),
    ('data_142','B1) Selecione um ou mais temas relacionados ao serviço [Inclusao de Pessoas com Deficiência]'),
    ('data_143','B1) Selecione um ou mais temas relacionados ao serviço [Infraestrutura]'),
    ('data_144','B1) Selecione um ou mais temas relacionados ao serviço [Inovação]'),
    ('data_145','B1) Selecione um ou mais temas relacionados ao serviço [Liderança]'),
    ('data_146','B1) Selecione um ou mais temas relacionados ao serviço [Logística]'),
    ('data_147','B1) Selecione um ou mais temas relacionados ao serviço [Orçamento/Finanças]'),
    ('data_148','B1) Selecione um ou mais temas relacionados ao serviço [Políticas Sociais]'),
    ('data_149','B1) Selecione um ou mais temas relacionados ao serviço [Projetos]'),
    ('data_150','B1) Selecione um ou mais temas relacionados ao serviço [Regulação]'),
    ('data_151','B1) Selecione um ou mais temas relacionados ao serviço [Tecnologia da Informação]'),
    ('data_152','B1) Selecione um ou mais temas relacionados ao serviço [Outros]'),
    ('data_153','B2) Nome do Serviço:'),
    ('data_154','B3) Descrição do Serviço:'),
    ('data_155','B4) Público: [Interno (Enap)]'),
    ('data_156','B4) Público: [Externo]'),
    ('data_157','B5) Instituições Envolvidas:'),
    ('data_158','B6) Fonte de Orçamento: [Orçamento da Enap]'),
    ('data_159','B6) Fonte de Orçamento: [TED]'),
    ('data_160','B6) Fonte de Orçamento: [Patrocínio]'),
    ('data_161','B6) Fonte de Orçamento: [Não Precisa De Orçamento]'),
    ('data_162','B6) Fonte de Orçamento: [A Definir]'),
    ('data_163','B6) Fonte de Orçamento: [Outros]'),
    ('data_164','B7) É um novo serviço?'),
    ('data_165','B8) A partir de que mês o serviço estará disponível?'),
    ('data_166','C1) Indique qual(is) produto(s) ou serviço(s) serão impactados pelo aperfeiçoamento:'),
    ('data_167','C2) Nome do aperfeiçoamento:'),
    ('data_168','C3) Descrição do Aperfeiçoamento:'),
    ('data_169','C4) Instituições Envolvidas:'),
    ('data_170','C5) Será necessária a aquisição ou contratação de algum serviço?'),
    ('data_171','C5.1) Como será feita essa aquisição/contratação? [Orçamento da Enap]'),
    ('data_172','C5.1) Como será feita essa aquisição/contratação? [TED]'),
    ('data_173','C5.1) Como será feita essa aquisição/contratação? [Patrocínio]'),
    ('data_174','C5.1) Como será feita essa aquisição/contratação? [A definir]'),
    ('data_175','C5.1) Como será feita essa aquisição/contratação? [Outros]'),
    ('data_176','C6) Mês da Entrega:'),
    ('data_177','2) Unidade líder'),
    ('data_178','3) Unidades Parceiras [Diretoria de Educação Continuada]'),
    ('data_179','3) Unidades Parceiras [-> Coordenação-Geral de Educação Executiva]'),
    ('data_180','3) Unidades Parceiras [-> Coordenação-Geral de Educação a Distância]'),
    ('data_181','3) Unidades Parceiras [Diretoria de Formação Profissional e Especialização]'),
    ('data_182','3) Unidades Parceiras [-> Coordenação-Geral de Formação]'),
    ('data_183','3) Unidades Parceiras [-> Coordenação-Geral de Especialização]'),
    ('data_184','3) Unidades Parceiras [-> Coordenação-Geral de Capacitação de Altos Executivos]'),
    ('data_185','3) Unidades Parceiras [Diretoria de Inovação e Gestão do Conhecimento]'),
    ('data_186','3) Unidades Parceiras [-> Coordenação-Geral de Gestão do Conhecimento]'),
    ('data_187','3) Unidades Parceiras [-> Coordenação-Geral de Inovação]'),
    ('data_188','3) Unidades Parceiras [-> Coordenação-Geral de Articulação Institucional]'),
    ('data_189','3) Unidades Parceiras [Diretoria de Pesquisa e Pós]'),
    ('data_190','3) Unidades Parceiras [-> Coordenação-Geral de Pós Graduação Stricto Sensu]'),
    ('data_191','3) Unidades Parceiras [-> Coordenação-Geral de Pesquisa]'),
    ('data_192','3) Unidades Parceiras [-> Coordenação-Geral de Ciência de Dados]'),
    ('data_193','3) Unidades Parceiras [Diretoria de Gestão Interna]'),
    ('data_194','3) Unidades Parceiras [-> Coordenação-Geral de Gestão de Pessoas e Adm]'),
    ('data_195','3) Unidades Parceiras [-> Coordenação-Geral de Orçamento, Finanças e Contabilidade]'),
    ('data_196','3) Unidades Parceiras [-> Coordenação-Geral de Tecnologia da Informação]'),
    ('data_197','3) Unidades Parceiras [Gabinete]'),
    ('data_198','3) Unidades Parceiras [-> Assessoria de Comunicação]'),
    ('data_199','3) Unidades Parceiras [-> Assessoria Internacional]'),
    ('data_200','3) Unidades Parceiras [-> Auditoria Interna]'),
    ('data_201','3) Unidades Parceiras [-> Procuradoria Federal]'),
    ('data_202','3) Unidades Parceiras [Comitê de Inclusão]'),
    ('data_203','3) Unidades Parceiras [Comitê de Gênero]'),
    ('data_204','3) Unidades Parceiras [Comissão De Ética]'),
    ('data_205','3) Unidades Parceiras [Comissão Gestora do Plano de Gestão de Logística Sustentável]'),
    ('data_206','4) Deseja adicionar observações sobre esta entrega?')
;

CREATE TABLE dadosPuros.dados (
    data_001 text,
    data_002 text,
    data_003 text,
    data_004 text,
    data_005 text,
    data_006 text,
    data_007 text,
    data_008 text,
    data_009 text,
    data_010 text,
    data_011 text,
    data_012 text,
    data_013 text,
    data_014 text,
    data_015 text,
    data_016 text,
    data_017 text,
    data_018 text,
    data_019 text,
    data_020 text,
    data_021 text,
    data_022 text,
    data_023 text,
    data_024 text,
    data_025 text,
    data_026 text,
    data_027 text,
    data_028 text,
    data_029 text,
    data_030 text,
    data_031 text,
    data_032 text,
    data_033 text,
    data_034 text,
    data_035 text,
    data_036 text,
    data_037 text,
    data_038 text,
    data_039 text,
    data_040 text,
    data_041 text,
    data_042 text,
    data_043 text,
    data_044 text,
    data_045 text,
    data_046 text,
    data_047 text,
    data_048 text,
    data_049 text,
    data_050 text,
    data_051 text,
    data_052 text,
    data_053 text,
    data_054 text,
    data_055 text,
    data_056 text,
    data_057 text,
    data_058 text,
    data_059 text,
    data_060 text,
    data_061 text,
    data_062 text,
    data_063 text,
    data_064 text,
    data_065 text,
    data_066 text,
    data_067 text,
    data_068 text,
    data_069 text,
    data_070 text,
    data_071 text,
    data_072 text,
    data_073 text,
    data_074 text,
    data_075 text,
    data_076 text,
    data_077 text,
    data_078 text,
    data_079 text,
    data_080 text,
    data_081 text,
    data_082 text,
    data_083 text,
    data_084 text,
    data_085 text,
    data_086 text,
    data_087 text,
    data_088 text,
    data_089 text,
    data_090 text,
    data_091 text,
    data_092 text,
    data_093 text,
    data_094 text,
    data_095 text,
    data_096 text,
    data_097 text,
    data_098 text,
    data_099 text,
    data_100 text,
    data_101 text,
    data_102 text,
    data_103 text,
    data_104 text,
    data_105 text,
    data_106 text,
    data_107 text,
    data_108 text,
    data_109 text,
    data_110 text,
    data_111 text,
    data_112 text,
    data_113 text,
    data_114 text,
    data_115 text,
    data_116 text,
    data_117 text,
    data_118 text,
    data_119 text,
    data_120 text,
    data_121 text,
    data_122 text,
    data_123 text,
    data_124 text,
    data_125 text,
    data_126 text,
    data_127 text,
    data_128 text,
    data_129 text,
    data_130 text,
    data_131 text,
    data_132 text,
    data_133 text,
    data_134 text,
    data_135 text,
    data_136 text,
    data_137 text,
    data_138 text,
    data_139 text,
    data_140 text,
    data_141 text,
    data_142 text,
    data_143 text,
    data_144 text,
    data_145 text,
    data_146 text,
    data_147 text,
    data_148 text,
    data_149 text,
    data_150 text,
    data_151 text,
    data_152 text,
    data_153 text,
    data_154 text,
    data_155 text,
    data_156 text,
    data_157 text,
    data_158 text,
    data_159 text,
    data_160 text,
    data_161 text,
    data_162 text,
    data_163 text,
    data_164 text,
    data_165 text,
    data_166 text,
    data_167 text,
    data_168 text,
    data_169 text,
    data_170 text,
    data_171 text,
    data_172 text,
    data_173 text,
    data_174 text,
    data_175 text,
    data_176 text,
    data_177 text,
    data_178 text,
    data_179 text,
    data_180 text,
    data_181 text,
    data_182 text,
    data_183 text,
    data_184 text,
    data_185 text,
    data_186 text,
    data_187 text,
    data_188 text,
    data_189 text,
    data_190 text,
    data_191 text,
    data_192 text,
    data_193 text,
    data_194 text,
    data_195 text,
    data_196 text,
    data_197 text,
    data_198 text,
    data_199 text,
    data_200 text,
    data_201 text,
    data_202 text,
    data_203 text,
    data_204 text,
    data_205 text,
    data_206 text
);
